### ISSUE TITLE
Typescript Issue in Node 10

### ISSUE THREAD

**Issue by scurker** [scurker/currency.js#180]
@scurker i can't make this work in node 10, need urgent help cause i can't deploy this...

using typescript latest version: 3.3.3 and version of currency.js 1.2.1

```bash
tsc -p tsconfig.build.json
```

tsconfig.build.json
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "sourceMap": false,
    "outDir": "./dist",
    "baseUrl": "./"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts", "**/*.test.ts"]
}
```

somefile.ts
```ts
import currency = require('currency.js');
```

node dist/main.js
```
/Users/ricardo/Code/payface-backend/services/src/face-transaction/entities/face-transaction-intention.entity.ts:3
import currency = require('currency.js');
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
 1: 0x10003ae75 node::Abort() [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 2: 0x1000b9707 node::Chdir(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 3: 0x10023035f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 4: 0x10022f8a1 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 5: 0x10022ef40 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/ricardo/.nodenv/versions/10.14.0/bin/node]
 6: 0x3adc122dbe3d
 7: 0x3adc122918d5
 8: 0x3adc12347578
```

if i change to **import * as currency from 'currency.js';** i get

```import * as currency from 'currency.js';
                  ^

SyntaxError: Unexpected token *
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
```

_Originally posted by @ricardovf in https://github.com/scurker/currency.js/issues/88#issuecomment-465256693_

**Comment by ricardovf** [comment]
Im really sorry, it was a error here, after 3 hours debugging. I had a dynamic config that looked for .ts files, and when running on node it tried to load .ts files and failed. Sorry, you can close.

**Comment by scurker** [comment]
No worries, glad you were able to resolve your issue!
